### ISSUE TITLE
Implement MQTT user and password as optional args

### ISSUE THREAD

**Issue by robmarkcole** [robmarkcole/rpi-enviro-mqtt#18]
Implement MQTT user and password as optional args. Note SSL is preferred but user and password is probably quite common  

Estimated complexity: pretty easy to implement but requires some testing, setup of appropriate broker etc. 1-2 hrs

References:
* http://www.steves-internet-guide.com/mqtt-username-password-example/
* https://www.eclipse.org/paho/index.php?page=clients/python/docs/index.php

**Comment by chpiero** [comment]
ok thanks, for now I have implemented without optional args. If I can implement it and I will pass you the code ... Thanks anyway for the availability

**Comment by robmarkcole** [comment]
> ok thanks, for now I have implemented without optional args. If I can implement it and I will pass you the code ... Thanks anyway for the availability

Can you provide link to your branch?

**Comment by peteretep** [comment]
Have opened a PR to the Pimoroni repo - https://github.com/pimoroni/enviroplus-python/pull/92

**Comment by robmarkcole** [comment]
thanks @peteretep !
