### ISSUE TITLE
Issue with import enviroplus

### ISSUE THREAD

**Issue by fotisK69** [robmarkcole/rpi-enviro-mqtt#19]
hi,

i have installed  pimoroni/enviroplus-python and rpi-enviro-mqtt but during execution it fails at the line 13:
from enviroplus import gas

pi@raspberrypi:~ $ python3 /home/pi/rpi-enviro-mqtt/mqtt-all.py --broker localhost --port 1883 --topic enviroplus --interval 5
Traceback (most recent call last):
  File "/home/pi/rpi-enviro-mqtt/mqtt-all.py", line 13, in <module>
    from enviroplus import gas
ModuleNotFoundError: No module named 'enviroplus'

Any clue?

**Comment by robmarkcole** [comment]
make sure you installed them in your python3 system environment, you probably installed them to python which defaults to python 2 on RPi
