### ISSUE TITLE
Running Home Assistant Along Side MQTT

### ISSUE THREAD

**Issue by TanukiKabuki** [robmarkcole/rpi-enviro-mqtt#20]
Curious at this deployment and whether or not you are running Home Assistant on the same Pi along side MQTT or how you have that all configured. There is no messaging feature so I apologize if this is not the way you'd prefer to communicate.

**Comment by robmarkcole** [comment]
I enabled Discussions if you want to start a thread there. I have MQTT broker and HA running on separate server
