### ISSUE TITLE
Enviro.service failing at boot

### ISSUE THREAD

**Issue by TanukiKabuki** [robmarkcole/rpi-enviro-mqtt#21]
This is what I am getting in terminal, I have checked the service config adjusted it between what is in your guide and what is on raspi org's site as well.
![image](https://user-images.githubusercontent.com/2154826/115811579-70586900-a39c-11eb-83b4-2c2f77d7bfc7.jpeg)
![image](https://user-images.githubusercontent.com/2154826/115811586-73ebf000-a39c-11eb-8233-b0e7422111c2.jpeg)
![image](https://user-images.githubusercontent.com/2154826/115811592-78180d80-a39c-11eb-8160-9f35d3e513a3.jpeg)

**Comment by robmarkcole** [comment]
I cant read alot of that, better to ssh to the device and then past some actual error messages

**Comment by TanukiKabuki** [comment]
Will retrieve those once I am home.

**Comment by robmarkcole** [comment]
stale closing
